(quail-define-package
 "baybayin" "UTF-8" "ᜊ" t
 "Baybayin input method."
 nil t nil nil nil nil nil nil nil nil t)

(quail-define-rules
 ("a" ["ᜀ"])
 ("b" ["ᜊ᜔"])
 ("ba" ["ᜊ"])
 ("be" ["ᜊᜒ"])
 ("bi" ["ᜊᜒ"])
 ("bu" ["ᜊᜓ"])
 ("bo" ["ᜊᜓ"])
 ("c" ["ᜃ᜔"])
 ("ca" ["ᜃ"])
 ("ce" ["ᜃᜒ"])
 ("ci" ["ᜃᜒ"])
 ("cu" ["ᜃᜓ"])
 ("co" ["ᜃᜓ"])
 ("d" ["ᜇ᜔"])
 ("da" ["ᜇ"])
 ("de" ["ᜇᜒ"])
 ("di" ["ᜇᜒ"])
 ("du" ["ᜇᜓ"])
 ("do" ["ᜇᜓ"])
 ("e" ["ᜁ"])
 ("f" ["ᜉ᜔"])
 ("fa" ["ᜉ"])
 ("fe" ["ᜉᜒ"])
 ("fi" ["ᜉᜒ"])
 ("fu" ["ᜉᜓ"])
 ("fo" ["ᜉᜓ"])
 ("g" ["ᜄ᜔"])
 ("ga" ["ᜄ"])
 ("ge" ["ᜄᜒ"])
 ("gi" ["ᜄᜒ"])
 ("gu" ["ᜄᜓ"])
 ("go" ["ᜄᜓ"])
 ("h" ["ᜑ᜔"])
 ("ha" ["ᜑ"])
 ("he" ["ᜑᜒ"])
 ("hi" ["ᜑᜒ"])
 ("hu" ["ᜑᜓ"])
 ("ho" ["ᜑᜓ"])
 ("i" ["ᜁ"])
 ("j" ["ᜐ᜔"])
 ("ja" ["ᜐ"])
 ("je" ["ᜐᜒ"])
 ("ji" ["ᜐᜒ"])
 ("ju" ["ᜐᜓ"])
 ("jo" ["ᜐᜓ"])
 ("k" ["ᜃ᜔"])
 ("ka" ["ᜃ"])
 ("ke" ["ᜃᜒ"])
 ("ki" ["ᜃᜒ"])
 ("ku" ["ᜃᜓ"])
 ("ko" ["ᜃᜓ"])
 ("l" ["ᜎ᜔"])
 ("la" ["ᜎ"])
 ("le" ["ᜎᜒ"])
 ("li" ["ᜎᜒ"])
 ("lu" ["ᜎᜓ"])
 ("lo" ["ᜎᜓ"])
 ("m" ["ᜋ᜔"])
 ("ma" ["ᜋ"])
 ("me" ["ᜋᜒ"])
 ("mi" ["ᜋᜒ"])
 ("mu" ["ᜋᜓ"])
 ("mo" ["ᜋᜓ"])
 ("n" ["ᜈ᜔"])
 ("na" ["ᜈ"])
 ("ne" ["ᜈᜒ"])
 ("ni" ["ᜈᜒ"])
 ("nu" ["ᜈᜓ"])
 ("no" ["ᜈᜓ"])
 ("ng" ["ᜅ᜔"])
 ("nga" ["ᜅ"])
 ("nge" ["ᜅᜒ"])
 ("ngi" ["ᜅᜒ"])
 ("ngu" ["ᜅᜓ"])
 ("ngo" ["ᜅᜓ"])
 ("o" ["ᜂ"])
 ("p" ["ᜉ᜔"])
 ("pa" ["ᜉ"])
 ("pe" ["ᜉᜒ"])
 ("pi" ["ᜉᜒ"])
 ("pu" ["ᜉᜓ"])
 ("po" ["ᜉᜓ"])
 ("q" ["ᜃ᜔"])
 ("qa" ["ᜃ"])
 ("qe" ["ᜃᜒ"])
 ("qi" ["ᜃᜒ"])
 ("qu" ["ᜃᜓ"])
 ("qo" ["ᜃᜓ"])
 ;; ("r" ["ᜇ᜔"])
 ;; ("ra" ["ᜇ"])
 ;; ("re" ["ᜇᜒ"])
 ;; ("ri" ["ᜇᜒ"])
 ;; ("ru" ["ᜇᜓ"])
 ;; ("ro" ["ᜇᜓ"])
 ("r" ["ᜍ᜔"])
 ("ra" ["ᜍ"])
 ("re" ["ᜍᜒ"])
 ("ri" ["ᜍᜒ"])
 ("ru" ["ᜍᜓ"])
 ("ro" ["ᜍᜓ"])
 ("s" ["ᜐ᜔"])
 ("sa" ["ᜐ"])
 ("se" ["ᜐᜒ"])
 ("si" ["ᜐᜒ"])
 ("su" ["ᜐᜓ"])
 ("so" ["ᜐᜓ"])
 ("t" ["ᜆ᜔"])
 ("ta" ["ᜆ"])
 ("te" ["ᜆᜒ"])
 ("ti" ["ᜆᜒ"])
 ("tu" ["ᜆᜓ"])
 ("to" ["ᜆᜓ"])
 ("u" ["ᜂ"])
 ("v" ["ᜊ᜔"])
 ("va" ["ᜊ"])
 ("ve" ["ᜊᜒ"])
 ("vi" ["ᜊᜒ"])
 ("vu" ["ᜊᜓ"])
 ("vo" ["ᜊᜓ"])
 ("w" ["ᜏ᜔"])
 ("wa" ["ᜏ"])
 ("we" ["ᜏᜒ"])
 ("wi" ["ᜏᜒ"])
 ("wu" ["ᜏᜓ"])
 ("wo" ["ᜏᜓ"])
 ("x" ["ᜋ᜔"])
 ("xa" ["ᜋ"])
 ("xe" ["ᜋᜒ"])
 ("xi" ["ᜋᜒ"])
 ("xu" ["ᜋᜓ"])
 ("xo" ["ᜋᜓ"])
 ("y" ["ᜌ᜔"])
 ("ya" ["ᜌ"])
 ("ye" ["ᜌᜒ"])
 ("yi" ["ᜌᜒ"])
 ("yu" ["ᜌᜓ"])
 ("yo" ["ᜌᜓ"])
 ("z" ["ᜎ᜔"])
 ("za" ["ᜎ"])
 ("ze" ["ᜎᜒ"])
 ("zi" ["ᜎᜒ"])
 ("zu" ["ᜎᜓ"])
 ("zo" ["ᜎᜓ"])
 ("," ["᜵"])
 ("." ["᜶"]))

(defvar tagalog-font-doctrina nil "Whether Doctrina 1593 Tagalog font is used")

(defun toggle-tagalog-font-doctrina ()
  "Set Tagalog font to Doctrina 1593"
  (interactive)
  (setq tagalog-font-doctrina (not tagalog-font-doctrina))
  (if tagalog-font-doctrina
    (set-fontset-font "fontset-default" 'tagalog (font-spec :family "Tagalog Doctrina 1593"))
    (set-fontset-font "fontset-default" 'tagalog (font-spec :family "Noto Sans Tagalog"))))

(set-fontset-font "fontset-default" 'tagalog (font-spec :family "Noto Sans Tagalog"))
;; ᜀ is for some reason not in Source Code Pro Semibold
;; (set-fontset-font "fontset-default" '(#x1700 . #x1700) (font-spec :family "Tagalog Doctrina 159"))

(provide 'language-baybayin)
